メッセージ送信機能　非同期化
shiratori-sh/chat-space pull request #11
Opened 2019-03-21 08:37 UTC by shiratori-sh

#WHAT
Jsファイル作成　非同期通信記述
コントローラーでレスポンス記述
Jbuileerファイル作成。キーとバリュー定義
modelにData-disable-with削除記述

Gif動画リンク
https://gyazo.com/ff08a4f5a0b4cefa4c574c23fc800ad0

#WHY

非同期通信を実装し必要な箇所だけ更新し動作を早くするため

2019-03-21 08:40 UTC, yuki-uchida requested changes

2019-03-21 08:40 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +  function buildHTML(message){
何のHTMLを組み立てるのかわかるような名前にしましょう

2019-03-21 08:40 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +    .done(function(data){
dataよりも具体的な名前にしましょう

2019-03-22 03:42 UTC, shiratori-sh commented on app/assets/javascripts/message.js
> +  function buildHTML(message){
・関数名を何のHTMLを組み立てるのかわかるよう変更しました。
$(function() {
  function HTML(message)
→$(function() {
  function messageHTML(message)

2019-03-22 03:42 UTC, shiratori-sh commented on app/assets/javascripts/message.js
> +    .done(function(data){
・引数の名称を具体的に何を示すのかわかる名称に変更しました。
 .done(function(data){
→ .done(function(message_data){

2019-03-22 03:45 UTC, miyagit approved these changes
LGTMです。

2019-03-22 03:48 UTC, shiratori-sh commented
ありがとうございます。マージします。

2019-03-22 03:48 UTC, merged